name: orange_gallery
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  animations: ^2.0.2
  lottie: ^1.2.1
  cupertino_icons: ^1.0.4


  
  fluttertoast: ^8.0.8
  google_nav_bar: ^5.0.5
  extended_image: ^6.0.1
  video_player: ^2.2.10
  
  share_plus: ^3.0.4
  hive: ^2.0.5
  provider: ^6.0.1
  photo_manager: ^1.3.10
  easy_localization: ^3.0.0
  
  
  path_provider: ^2.0.8
  external_path: ^1.0.1
  package_info: ^2.0.2
  permission_handler: ^8.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
 
  

flutter:
  generate: true 
  uses-material-design: true

  assets:
  - assets/translations/
  - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf 
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 700

    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf
    
